sylius_grid:
    templates:
        action:
            apply_transition: "@SyliusUi/Grid/Action/applyTransition.html.twig"
    grids:
        app_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.model.supplier.class%"
                    
            sorting:
                name: asc
            fields:
                id:
                    type: string
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                state:
                    type: string
                email:
                    type: string
                    label: Email
                    sortable: ~
            filters:
                name:
                    type: string
                email:
                    type: string
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

                    verify:
                        type: apply_transition
                        label: sylius.ui.accept
                        icon: checkmark
                        options:
                            link:
                                route: app_supplier_verify
                                parameters:
                                    id: resource.id
                            class: green
                            transition: verify
                            graph: app_supplier
                            
                    unverify:
                        type: apply_transition
                        label: sylius.ui.reject
                        icon: remove
                        options:
                            link:
                                route: app_supplier_unverify
                                parameters:
                                    id: resource.id
                            class: yellow
                            transition: unverify
                            graph: app_supplier
