winzou_state_machine:
    app_supplier:
        class: "%app.model.supplier.class%"
        property_path: state
        graph: app_supplier
        state_machine_class: "%sylius.state_machine.class%"
        states:
            verified: ~
            unverified: ~
        transitions:
            verify:
                from: [unverified]
                to: verified
            unverify:
                from: [verified]
                to: unverified
        callbacks:
            after:
                email_notification:
                    on: 'verify'
                    do: ['@App\Listener\SupplierNotifier', '__invoke']
                    args: ['object']

