app_supplier:
    resource: |
        alias: app.supplier
        section: admin # app_ADMIN
        path: admin/supplier # prefix with /admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: app_supplier
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'file image outline'
    type: sylius.resource

app_supplier_verify:
    path: /admin/supplier/{id}/verify
    methods: [PUT]
    defaults:
        _controller: app.controller.supplier:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: app_supplier
                transition: verify
            redirect: referer
            flash: sylius.review.accept

app_supplier_unverify:
    path: /admin/supplier/{id}/unverify
    methods: [PUT]
    defaults:
        _controller: app.controller.supplier:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: app_supplier
                transition: unverify
            redirect: referer
            flash: sylius.review.reject
